### ISSUE TITLE
Leaflet.TitleLayer.Swiss

### ISSUE THREAD

**Issue by pythonpoet** [rkaravia/Leaflet.TileLayer.Swiss#1]
First things first, complements for your great work.

I have a question, hope you can answer it. 
For a project i use Flutter, a tool to create mobile applications. I came a cross a plugin witch can display openstreetmaps (https://pub.dev/packages/flutter_map) It works with leaflet. With that in mind i hoped, that i could use the geo.admin map as a layer.

Originaly the layer with Openstretmap looks like this:
```
FlutterMap(
                options: MapOptions(
                  center: LatLng(47.366, 8.2537),
                  zoom: 5.0,
                 
                ),
                layers: [
                  TileLayerOptions(
                      urlTemplate:
                          'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                      subdomains: ['a', 'b', 'c']),
                 
                ],
              ),
```

My suggestion was, i could just copy and paste your link into the urlTemplate like this:
```
FlutterMap(
                options: MapOptions(
                  center: LatLng(47.366, 8.2537),
                  zoom: 5.0,
                ),
                layers: [
                  TileLayerOptions(
                      urlTemplate:
                          'https://wmts{s}.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/2056/{z}/{x}/{y}.jpeg',
                      subdomains: ['0123456789']),
                  MarkerLayerOptions(markers: markers)
                ],
              ),
```
obviously this dosn't work, but i hope there is an easy way to get it working. 
Do you have any suggestions?

**Comment by rkaravia** [comment]
Yes, indeed it looks like flutter_map is not actually based on Leaflet, but is a dart-port of Leaflet, so you would also have to port all code in this plugin in order to use it with flutter_map.

An easier solution might be to use the web mercator maps from swisstopo, which should be compatible with flutter_map, the URL (documented [here](https://api3.geo.admin.ch/services/sdiservices.html#supported-projections)) is:
https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg
