### ISSUE TITLE
Non-minified version

### ISSUE THREAD

**Issue by claudep** [rkaravia/Leaflet.TileLayer.Swiss#3]
Hi,
I have an issue with a layer causing a never-ending loop during projection step (looks like the loop is in fromCartesian in swissgrid, reproducible with Chrome but not Firefox). It would be easier to debug with a non-minified version of Leaflet.TileLayer.Swiss. Do you have instructions for using such a non-minified version?

**Comment by claudep** [comment]
(note that you can try the original issue as the url is public: https://schauenburg.guaraci.ch/public/map/?layer=altholz)

**Comment by rkaravia** [comment]
Thank you for the report!

It looks like you are using an older version of Leaflet.TileLayer.Swiss (v2.1.0). Please try again with the latest version (v2.2.1), I believe the issue has been fixed.

About a non-minified version: You could build one by removing [these two lines](https://github.com/rkaravia/Leaflet.TileLayer.Swiss/blob/v2.2.1/rollup.config.js#L45-L46), but the swissgrid part would probably still be minified, since swissgrid currently only has a minified build.

**Comment by rkaravia** [comment]
Looks like it's working now with the latest version :-)

**Comment by claudep** [comment]
Sure, thanks a lot!
